src/py_zfs_object.c

Add some docstrings for the attributes of the base ZFS dataset object. Actual text is mostly copy-paste from the manpage for zfsprops(7).

Add pydoc strings for ZFS object getters

---

src/py_zfs_iter.c
src/py_zfs_iter.h

This commit adds pointer to stored thread state in pylibzfs iterator state struct. Two macros are also added to simplify toggling GIL in iterators and comments are added to clarify how to write a new iterator.

Manage GIL state in libzfs iterators

---

src/py_zfs_iter.c

Set resource is_simple if iterator was called with flag to create simple handles. This properly indicates that ZFSDataset object will not have full properties initialized.

properly flag simple handle

---

src/pylibzfs2.c
src/pylibzfs2.h
src/utils.c

enum.IntEnum works better for this purpose because it allows library consumers to look up the thing by either name or value.

Convert int constants from lookup tables to IntEnum

---

setup.py
src/pylibzfs2.c
src/pylibzfs2.h
src/pylibzfs2_enums.h
src/utils.c

This commit does the following:
* exposes various libzfs constants at module level
* adds enum.IntEnum for zfs_type_t
* adds enum.IntFlag for ZFS DOS flags
* exposes IOCTL numbers for interacting with ZFS DOS flags
* renames module from pylibzfs2 to truenas_pylibzfs

Expand enums / constants for pylibzfs2

---

src/py_zfs.c
src/py_zfs_pool.c
src/pylibzfs2.h

This commit adds basic functionality for ZFSPool.
* Open the pool and return ZFSPool object
* Stores pool name as python str
* Return ZFSDataset object for root dataset
* Implements zpool clear
* Implements zpool delete
* Implements zpool upgrade
* Implements zpool prefetch
* Implements zpool ddt_prune

Add basic zpool functionality for ZFSPool

---

src/py_zfs.c
src/pylibzfs2.h

Copy the history prefix into a pre-allocated buffer in the ZFS object struct. This avoids potential for UAF once the python unicode object under which the prefix string is garbage collected.

Fix buffer for history prefix in ZFS object

---

src/py_zfs_object.c
src/pylibzfs2.h
src/utils.c

This commit retries to log zpool history in case of failure with EINTR in which the python signal handler hasn't caught the signal and already set an exception. Otherwise, a RuntimeError is set with the missing zpool history line and OS error information.

Improve error handling in zpool_log_history

---

setup.py
src/py_zfs_dataset.c
src/py_zfs_object.c
src/py_zfs_state.c
src/py_zfs_state.h
src/pylibzfs2.c
src/pylibzfs2.h

This commit makes the following changes:
* Adds a backpointer to py_zfs_t objects to the originating module object. This required changing how truenas_pylibzfs.ZFS objects are created (now via a module method rather than calling the object).
* Adds a utility function to get a pointer to the module state struct based on a give py_zfs_t object.
* Defines struct for py_zfs_state and adds lookup table for converting zfs_type_t to new reference of truenas_pylibzfs.ZFSType object.
* Adds docstring for `truenas_pylibzfs.open_handle` module method.

Add module state struct and improve ZFS dataset object

---

setup.py
src/py_zfs_pool.c
src/py_zfs_vdev.c
src/pylibzfs2.c
src/pylibzfs2.h

This commit adds a Python type for vdevs, ZFSVdev. Some baisc operations have been implemented. Ability to retrieve root vdev from ZFSPool object is also added.

Add ZFSVdev object for handling vdevs

---

src/py_zfs.c
src/py_zfs_pool.c

This PR adds:
* Audit events and zpool history logs for ZFSPool operations
* Doc strings have been added for ZFSPool methods and attributes
* Fixed an issue in `ddt_prune` operation

Add history and audit logs for ZFSPool

---

setup.py
src/py_zfs.c
src/py_zfs_iter.c
src/py_zfs_resource.c
src/py_zfs_volume.c
src/truenas_pylibzfs.c
src/truenas_pylibzfs.h

This commit python definitions for zvols and shifts the filesystem iterator to the parent ZFS resource type for datasets and zvols to avoid code duplication.

Add ZFS volume object

---

src/truenas_pylibzfs.c

We don't need constants cluttering up base of module. Move them to sub-module that's stored in base module.

Shift constants to truenas_pylibzfs.constants

---

src/py_zfs.c
src/py_zfs_dataset.c
src/py_zfs_enum.c
src/py_zfs_prop.c
src/py_zfs_resource.c
src/py_zfs_state.c
src/py_zfs_state.h
src/truenas_pylibzfs.c
src/truenas_pylibzfs.h
src/truenas_pylibzfs_enums.h

This adds common methods and utility functions for getting ZFS properties.

Add ability to get ZFS object properties

---

src/error.c
src/libzfs_core/py_zfs_core_module.c
src/truenas_pylibzfs.h

This commit adds python wrappers for lzc_snapshot() and lzc_destroy_snaps() with appropriate documentation and exception handling. A new module exception type was added due to significant differences between errors from libzfs and libzfs_core.
The new exception includes tuple containing snapshots for which the bulk operation failed.

Add support for bulk snapshot operations

---

setup.py
src/libzfs/py_zfs_resource.c
src/nvlist_utils.c
src/truenas_pylibzfs.h

This commit adds basic functionality to get and set ZFS user properties. These are treated exposed separately from regular ZFS properties for performance and convenience reasons. get_user_properties is also plumbed into the asdict() method for ZFS resources.

Add ability to get / set user properties

---

setup.py
src/libzfs/py_zfs.c
src/libzfs/py_zfs_snapshot.c
src/truenas_pylibzfs.c
src/truenas_pylibzfs.h

This commit adds basic functionality to open a ZFS snapshot. At this point no type methods or getsetters are defined.

Add ZFSSnapshot type and allow opening it

---

src/libzfs/py_zfs_snapshot.c
src/nvlist_utils.c
src/truenas_pylibzfs.h

This commit adds type method for ZFSSnapshot type to get the clones of the snapshot. Type returned is always a tuple.
```
>>> import truenas_pylibzfs
>>> z = truenas_pylibzfs.open_handle()
>>> rsrc = z.open_resource(name="dozer/myzv@now")
>>> rsrc.get_clones()
('dozer/newzv',)
```

Add method to get clones of ZFS snapshot

---

examples/user_hold_context_manager.py
src/libzfs/py_zfs_snapshot.c
src/libzfs_core/py_zfs_core_module.c

This commit fixes a memory leak when retrieving ZFS holds for a snapshot (we weren't freeing the nvlist returned by libzfs_core). This also fixes some syntax errors in the example script for managing user holds.

Fix memory leak in libzfs_core

---

examples/get_space_stats.py
setup.py
src/libzfs/py_zfs_resource.c
src/property_sets/py_zfs_prop_sets.c
src/truenas_pylibzfs.c
src/truenas_pylibzfs.h

This commit creates a submodule "property_sets" and adds various frozenset sets of properties for end-users to use when retrieving ZFS properties. An example is also added to show how to use property sets when retrieving dataset information recursively.

Add some pre-defined property sets

---

src/common/nvlist_utils.c
src/libzfs/py_zfs.c
src/libzfs/py_zfs_resource.c
src/truenas_pylibzfs.h

This commit normalizes zfs properties via JSON dump of the properties nvlist prior to writing a zpool history message.
In the process of adding this a general-purpose function has been introduced to convert an nvlist into a python unicode object via libzfs nvlist dump functions (either generic pretty-printed or as JSON).

Normalize properties for zpool history messages

---

examples/recursive_snapshot.py
src/libzfs_core/py_zfs_core_module.c

This commit exposes ability to set user properties when using the create_snapshots endpoint. This can be used to indicate application-specific information about a particular recursive snapshot tasks.

Add ability to set custom user properties on bulk snaps

---

src/common/nvlist_utils.c

I had a reading comprehension failure when reading open_memstream(3) manpage and introduced a memory
leak caught by valgrind.

Free dynamic memory buffer for nvlist dump

---

examples/filterable_query.py
src/libzfs/py_zfs_resource.c

This commit provides a reference implementation of using middleware query-filters and query-options in the context of libzfs iterator callback functions.

Add a more robust example of query-filters

---

examples/iter_root_datasets.py
src/libzfs/py_zfs.c
src/libzfs/py_zfs_iter.c
src/libzfs/py_zfs_iter.h
src/truenas_pylibzfs_state.c
src/truenas_pylibzfs_state.h

This commit adds a root dataset iterator for the base of the module. This is useful for recursive operations on all imported pools.

Add iterator for root datasets

---

src/libzfs/py_zfs_prop.c

Fix 2 issues:
1. a spurious RuntimeError is raised when trying to retrieve the resume token property of a filesystem
2. remove the verbiage that mentions "for dataset." since that's a bit of a misnomer in this given context.

fix RuntimeError on resume_receive_token prop

---

examples/filterable_query.py

This simply improves the filterable query example and adds a recursive example. I also use `pprint.pprint` to format the output as I find it easier to read.

Improve query example and add recursive functionality

---

examples/iter_root_filesystems.py
src/libzfs/py_zfs.c
src/libzfs/py_zfs_iter.c
src/libzfs/py_zfs_iter.h

This renames the user-facing `iter_root_datasets` method to `iter_root_filesystems`. This follows convention with other user-facing methods.

iter_root_datasets -> iter_root_filesystems

---

src/libzfs/py_zfs.c

The user-facing method is called `pool_open`. There is no need to enforce the keyword argument to be named "pool_name" as it's redundant. Furthermore, the convention followed in other user-facing methods is to use the `name` kwarg. This converts it from `pool_name` to `name` to match convention.

change pool_name kwarg to name

---

src/libzfs/py_zfs_iter.c
src/libzfs/py_zfs_userquota.c
src/truenas_pylibzfs.h

This commit fixes two issues with ZFS userspace:
* Reference counting bug in truenas-pylibzfs when creating
struct userspace quota
* Invalid function definition for zfs_userspace_cb_t. Introduced
by not accounting for upstream changes in the aforementioned
callback type.

Fix crash in ZFS userspace

---

src/libzfs/py_zfs_crypto.c
src/libzfs/py_zfs_dataset.c
src/libzfs/py_zfs_object.c
src/libzfs/py_zfs_snapshot.c
src/libzfs/py_zfs_volume.c
src/truenas_pylibzfs.h

This commit optimizes lookups for ZFS dataset crypto information by adding a boolean value to the root of dataset to indicate whether it's encrypted and short-circuit retrieval of crypto object.
A new attribute for ZFS objects `encrypted` is also added.
```
>>> rsrc = hdl.open_resource(name='dozer/ENC')
>>> rsrc.encrypted
True
```

Optimize reading resource crypto information

---

src/libzfs_core/py_zfs_core_module.c

This commit fixes several cases in libzfs_core module where failed audit messages could leak memory.

NAS-136100 / 25.10 / Fix memory leaks on auditing failures

---

src/libzfs/py_zfs_crypto.c
src/truenas_pylibzfs_state.c
src/truenas_pylibzfs_state.h

This commit adds a change_key method to the ZFS cryptography object, which may be used to rewrap the crypto key on an existing encrypted ZFS resource (dataset or volume). It also creates a new struct sequence object for cryptography information that will be consumed when creating new encrypted resources.

NAS-136891 / 25.10 / Add method to change crypto key

---

src/libzfs/py_zfs_iter.c

If a dataset is unmounted then the zfs_userspace related ZFS ioctls may fail with EZFS_BUSY depending on timing. In this case we can generally retry after a slight wait and succeed. This commit adds logic to usleep for up to 5 seconds while trying to start iteration. This addresses potential spurious errors that can filter up to library consumers such as the TrueNAS middleware / UI if multiple concurrent requests are issued for different quota types on the same unmounted dataset.

NAS-137068 / 26.04 / Add retry logic for zfs_userspace iterator

---

examples/create_encrypted_dataset.py
src/libzfs/py_zfs.c
src/libzfs/py_zfs_crypto.c
src/truenas_pylibzfs.h

* Add ability to create encrypted resources by passing "crypto" keyword argument to create_resource() with properly filled-out ZFS cryptography information struct
* Convert the rekey API to use the cryptography information struct
* Reduce code duplication
Original PR: https://github.com/truenas/truenas_pylibzfs/pull/77

NAS-137045 / 25.10-RC.1 / Add ability to create encrypted ZFS resources (by anodos325)

---

examples/encryption.py
src/libzfs/py_zfs_crypto.c

This commit adds a new crypto object method `check_key` that returns a boolean value indicating whether the provided crypto material can be used to unlock the resource.

NAS-137070 / 26.04 / Improve the API for testing crypto keys

---

examples/encryption.py
src/libzfs/py_zfs_crypto.c

This commit adds a new crypto object method `check_key` that returns a boolean value indicating whether the provided crypto material can be used to unlock the resource.
Original PR: https://github.com/truenas/truenas_pylibzfs/pull/82

NAS-137070 / 25.10-RC.1 / Improve the API for testing crypto keys (by anodos325)

---

examples/channel_program.py
src/libzfs_core/lua_channel_programs.h

This commit adds a channel program to destroy snapshots atomically and expands examples.
Original PR: https://github.com/truenas/truenas_pylibzfs/pull/101

NAS-137264 / 25.10-RC.1 / Add channel program to destroy snapshots (by anodos325)

---

src/libzfs/py_zfs_prop.c
src/libzfs/py_zfs_resource.c
src/truenas_pylibzfs.h

This commit adds a util function to convert a python unicode object or a truenas_pylibzfs.ZFSProperty object into zfs_prop_t, and also adds an inherit_property() function to ZFS resource objects.

NAS-137476 / 26.04 / Add function to inherit ZFS properties
